// <auto-generated />
using System;
using GestionFournituresAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250601121115_AddUserAssociations")]
    partial class AddUserAssociations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionFournituresAPI.Models.Agence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NUMERO");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("AGENCES");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.AgenceFourniture", b =>
                {
                    b.Property<int>("AgenceId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGENCE_ID");

                    b.Property<int>("FournitureId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FOURNITURE_ID");

                    b.Property<DateTime>("DateAssociation")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_ASSOCIATION");

                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    b.Property<int>("Quantite")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITE");

                    b.HasKey("AgenceId", "FournitureId");

                    b.HasIndex("FournitureId");

                    b.ToTable("AGENCE_FOURNITURE", "SYSTEM");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Amortissement", b =>
                {
                    b.Property<int>("IdAmortissement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AMORTISSEMENT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAmortissement"));

                    b.Property<int>("Annee")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANNEE");

                    b.Property<DateTime>("DateCalcul")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_CALCUL");

                    b.Property<int>("IdBien")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_BIEN");

                    b.Property<decimal>("Montant")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("MONTANT");

                    b.Property<decimal>("ValeurResiduelle")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VALEUR_RESIDUELLE");

                    b.HasKey("IdAmortissement");

                    b.HasIndex("IdBien", "Annee")
                        .IsUnique();

                    b.ToTable("AMORTISSEMENTS");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.BienAgence", b =>
                {
                    b.Property<int>("IdBien")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_BIEN");

                    b.Property<int>("IdAgence")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AGENCE");

                    b.Property<DateTime>("DateAffectation")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_AFFECTATION");

                    b.Property<int?>("Quantite")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITE");

                    b.HasKey("IdBien", "IdAgence", "DateAffectation");

                    b.HasIndex("IdAgence");

                    b.ToTable("BIEN_AGENCE");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Categorie", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CATEGORIE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategorie"));

                    b.Property<int>("DureeAmortissement")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DUREE_AMORTISSEMENT");

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM_CATEGORIE");

                    b.HasKey("IdCategorie");

                    b.ToTable("CATEGORIES");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.EntreeFourniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_ENTREE");

                    b.Property<int>("FournitureId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FOURNITURE_ID");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MONTANT");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRIX_UNITAIRE");

                    b.Property<int>("QuantiteEntree")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITE_ENTREE");

                    b.HasKey("Id");

                    b.HasIndex("FournitureId");

                    b.ToTable("ENTREE_FOURNITURES", "SYSTEM");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Fourniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CATEGORIE");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRIX_UNITAIRE");

                    b.Property<int>("QuantiteRestante")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITE_RESTANTE");

                    b.HasKey("Id");

                    b.ToTable("FOURNITURES", "SYSTEM");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Immobilisation", b =>
                {
                    b.Property<int>("IdBien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_BIEN");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBien"));

                    b.Property<string>("CodeBarre")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CODE_BARRE");

                    b.Property<DateTime?>("DateAcquisition")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_ACQUISITION");

                    b.Property<int?>("IdCategorie")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CATEGORIE");

                    b.Property<string>("NomBien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM_BIEN");

                    b.Property<int?>("Quantite")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITE");

                    b.Property<string>("Statut")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUT");

                    b.Property<decimal>("TauxAmortissement")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TAUX_AMORTISSEMENT");

                    b.Property<decimal>("ValeurAcquisition")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VALEUR_ACQUISITION");

                    b.HasKey("IdBien");

                    b.HasIndex("IdCategorie");

                    b.ToTable("IMMOBILISATIONS");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Fonction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("FONCTION");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MOT_DE_PASSE");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PRENOM");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USERS", "SYSTEM");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.UserAgence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenceId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGENCE_ID");

                    b.Property<DateTime>("DateAssociation")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_ASSOCIATION");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("AgenceId");

                    b.HasIndex("UserId");

                    b.ToTable("USER_AGENCE", "SYSTEM");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.UserFourniture", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.Property<int>("FournitureId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FOURNITURE_ID");

                    b.Property<DateTime>("DateAssociation")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_ASSOCIATION");

                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    b.HasKey("UserId", "FournitureId");

                    b.HasIndex("FournitureId");

                    b.ToTable("USER_FOURNITURE", "SYSTEM");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.AgenceFourniture", b =>
                {
                    b.HasOne("GestionFournituresAPI.Models.Agence", "Agence")
                        .WithMany("AgenceFournitures")
                        .HasForeignKey("AgenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFournituresAPI.Models.Fourniture", "Fourniture")
                        .WithMany("AgenceFournitures")
                        .HasForeignKey("FournitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agence");

                    b.Navigation("Fourniture");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Amortissement", b =>
                {
                    b.HasOne("GestionFournituresAPI.Models.Immobilisation", "Immobilisation")
                        .WithMany("Amortissements")
                        .HasForeignKey("IdBien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Immobilisation");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.BienAgence", b =>
                {
                    b.HasOne("GestionFournituresAPI.Models.Agence", "Agence")
                        .WithMany("BienAgences")
                        .HasForeignKey("IdAgence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFournituresAPI.Models.Immobilisation", "Immobilisation")
                        .WithMany("BienAgences")
                        .HasForeignKey("IdBien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agence");

                    b.Navigation("Immobilisation");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.EntreeFourniture", b =>
                {
                    b.HasOne("GestionFournituresAPI.Models.Fourniture", "Fourniture")
                        .WithMany("EntreesFournitures")
                        .HasForeignKey("FournitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fourniture");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Immobilisation", b =>
                {
                    b.HasOne("GestionFournituresAPI.Models.Categorie", "Categorie")
                        .WithMany("Immobilisations")
                        .HasForeignKey("IdCategorie");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.UserAgence", b =>
                {
                    b.HasOne("GestionFournituresAPI.Models.Agence", "Agence")
                        .WithMany("UserAgences")
                        .HasForeignKey("AgenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFournituresAPI.Models.User", "User")
                        .WithMany("UserAgences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.UserFourniture", b =>
                {
                    b.HasOne("GestionFournituresAPI.Models.Fourniture", "Fourniture")
                        .WithMany("UserFournitures")
                        .HasForeignKey("FournitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFournituresAPI.Models.User", "User")
                        .WithMany("UserFournitures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fourniture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Agence", b =>
                {
                    b.Navigation("AgenceFournitures");

                    b.Navigation("BienAgences");

                    b.Navigation("UserAgences");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Categorie", b =>
                {
                    b.Navigation("Immobilisations");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Fourniture", b =>
                {
                    b.Navigation("AgenceFournitures");

                    b.Navigation("EntreesFournitures");

                    b.Navigation("UserFournitures");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Immobilisation", b =>
                {
                    b.Navigation("Amortissements");

                    b.Navigation("BienAgences");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.User", b =>
                {
                    b.Navigation("UserAgences");

                    b.Navigation("UserFournitures");
                });
#pragma warning restore 612, 618
        }
    }
}
