// <auto-generated />
using System;
using GestionFournituresAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionFournituresAPI.Models.Agence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NUMERO");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("AGENCES", "SYSTEM");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.AgenceFourniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenceId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGENCE_ID");

                    b.Property<DateTime>("DateAssociation")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_ASSOCIATION");

                    b.Property<int>("FournitureId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FOURNITURE_ID");

                    b.HasKey("Id");

                    b.HasIndex("AgenceId");

                    b.HasIndex("FournitureId");

                    b.ToTable("AGENCE_FOURNITURE", "SYSTEM");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Fourniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CATEGORIE");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MONTANT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM");

                    b.Property<decimal>("PrixTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRIX_TOTAL");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRIX_UNITAIRE");

                    b.Property<int>("Quantite")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITE");

                    b.Property<int>("QuantiteRestante")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITE_RESTANTE");

                    b.HasKey("Id");

                    b.ToTable("FOURNITURES", "SYSTEM");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenceId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGENCE_ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MOT_DE_PASSE");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PRENOM");

                    b.HasKey("Id");

                    b.HasIndex("AgenceId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USERS", "SYSTEM");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.AgenceFourniture", b =>
                {
                    b.HasOne("GestionFournituresAPI.Models.Agence", "Agence")
                        .WithMany("AgenceFournitures")
                        .HasForeignKey("AgenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFournituresAPI.Models.Fourniture", "Fourniture")
                        .WithMany("AgenceFournitures")
                        .HasForeignKey("FournitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agence");

                    b.Navigation("Fourniture");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.User", b =>
                {
                    b.HasOne("GestionFournituresAPI.Models.Agence", "Agence")
                        .WithMany("Users")
                        .HasForeignKey("AgenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agence");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Agence", b =>
                {
                    b.Navigation("AgenceFournitures");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GestionFournituresAPI.Models.Fourniture", b =>
                {
                    b.Navigation("AgenceFournitures");
                });
#pragma warning restore 612, 618
        }
    }
}
